Repository keycloud/keycloud, pull requests merged in 2020-06, with the labels that each got.

#60 Update backend-calls.md
  server/docs/backend-calls.md
Labels: bug

#66 Add nginx rp to docker-compose
  server/docker-compose-alt.yml
  server/nginx.conf
  server/nginx/error.log
Labels: enhancement

#71 Add 2FA status
  server/crudHandler.go
  server/crudHandler_test.go
  server/database.go
  server/docs/backend-calls.md
  server/storage.go
  server/storageInterface.go
Labels: documentation, enhancement

#68 Fix typo
  server/.env
Labels: bug

#67 Add help dialog, change calls to be relative to host address
  dashboard/src/app/app.component.html
  dashboard/src/app/app.module.ts
  dashboard/src/app/dashboard/confirmation.component.html
  dashboard/src/app/dialog/dialog.component.html
  dashboard/src/app/login/login.component.ts
  dashboard/src/app/models/user.spec.ts
  dashboard/src/app/models/user.ts
  dashboard/src/app/settings/help.component.html
  dashboard/src/app/settings/settings.component.html
  dashboard/src/app/settings/settings.component.spec.ts
  dashboard/src/app/settings/settings.component.ts
  dashboard/src/environments/environment.prod.ts
  dashboard/src/environments/environment.ts
Labels: feature

#73 Fix user-service test
  dashboard/src/app/services/user.service.spec.ts
Labels: bug

#74 Add chrome fill in plugin
  plugins/KeyCloudChromePlugin/content.js
  plugins/KeyCloudChromePlugin/dashboard.js
  plugins/KeyCloudChromePlugin/index.html
  plugins/KeyCloudChromePlugin/manifest.json
  plugins/KeyCloudChromePlugin/popup.html
  plugins/KeyCloudChromePlugin/popup.js
Labels: feature
